sudo: required
services: 
  - docker

before_install:
  - docker build -t MounirChennana/react-test -f ./client/Dockerfile.dev
 
script:
  - docker run MounirChenna/react-test npm test  -- --coverage

after_success:
  - docker build -t MounirChennana/multi-client ./client
  - docker build -t MounirChennana/multi-nginx ./nginx
  - docker build -t MounirChennana/multi-server ./server
  - docker build -t MounirChennana/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$Docker_ID" --password-stdin

  - docker push MounirChenna/multi-client
  - docker push MounirChennana/multi-nginx
  - docker push MounirChennana/multi-server
  - docker push MounirChennana/multi-worker